spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://@youngho-db-001.c3g4wc00ay9v.ap-northeast-2.rds.amazonaws.com/futurefinder
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # update, create
    properties:
      hibernate:
        format_sql: true   # ✅ 이렇게!

# jdbc:mysql://@youngho-db-001.c3g4wc00ay9v.ap-northeast-2.rds.amazonaws.com/futurefinder
# jdbc:mysql://localhost:3306/futurefinder