spring:
  datasource:
    url: jdbc:mysql://localhost:3306/futurefinder
    username: ff_user
    password: ff_pass_123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # update, create
    properties:
      hibernate:
        format_sql: true   # ✅ 이렇게!